### ISSUE TITLE
System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by cruz0** [NAXAM/afnetworking-ios-binding#1]
This message of expeption appears when using AFHTTPSessionManager.Manager().RequestSerializer object.

Code:
```
var manager = AFHTTPSessionManager.Manager();
System.Diagnostics.Debug.WriteLine(manager.RequestSerializer);
```
and application  crash

**Comment by tuyen-vuduc** [comment]
This binding library isnt for use directly. Plz use HttpClient to work with remote API in Xamarin.
